platform :ios, '8.0'

target 'FYHelperDemo' do

  # 版本更新控制 自动更新的第三方库
  # 地址: https://github.com/nicklockwood/iVersion
  pod 'iVersion'


# 网络请求相关专用库
# 地址: https://github.com/AFNetworking/AFNetworking
  pod 'AFNetworking'
  pod 'AFNetworkActivityLogger'

##################################################

# SVSegmentedControl is a customizable UIControl class that mimics UISegmentedControl but that looks like an UISwitch.
# 地址: https://github.com/samvermette/SVSegmentedControl

# pod 'SVSegmentedControl'

##################################################

# 一种segmented control
# 地址: https://github.com/pepibumur/PPiFlatSegmentedControl

# pod 'PPiFlatSegmentedControl', :git => 'https://github.com/pepibumur/PPiFlatSegmentedControl.git'

##################################################

# 加载时动画
# 地址: https://github.com/jdg/MBProgressHUD
  pod 'MBProgressHUD', '~> 1.0.0'

##################################################

# 显示popview 提示消息.(可以用标题加内容的方式突出重点)
# 地址: https://github.com/toursprung/TSMessages

# pod 'TSMessages'
# pod 'TSMessages', :git => 'https://github.com/iosfeng/TSMessages.git'

# pod 'RMessage'
# pod 'RMessage', :git => 'https://github.com/iosfeng/RMessage.git'

##################################################

# 数据模型框架,相当不错的.
# 地址: https://github.com/icanzilb/JSONModel

# pod 'JSONModel'

##################################################

# 异步下载 缓存 图片的
# 地址: https://github.com/rs/SDWebImage

# pod 'SDWebImage'

##################################################

# 实现一些自定义效果的UILabel
# 地址: https://github.com/mattt/TTTAttributedLabel

# pod 'TTTAttributedLabel'

##################################################

# An open source Objective-C interface component
# that makes use of the CoreText framework to render
# static text content using a highly customisable markup syntax.
# 地址:https://github.com/FuerteInternational/FTCoreText

# pod 'FTCoreText'

##################################################

# 图片浏览器
# 地址: https://github.com/mwaterfall/MWPhotoBrowser

# pod 'MWPhotoBrowser'

##################################################

# 图片选择器-[由于要修改源码,放vendors中管理]
# 地址: https://github.com/chiunam/CTAssetsPickerController

# pod 'CTAssetsPickerController',  '~> 2.3.0'

##################################################

# 轻量级 浏览器
# 地址: https://github.com/TimOliver/TOWebViewController

# pod 'TOWebViewController'

##################################################

# 友盟 SDK
# 地址: http://dev.umeng.com/analytics/ios-doc/integration

  # pod 'UMengAnalytics'

# pod 'UMengFeedback', '~> 2.3.3'
# pod 'UMengMessage', '~> 1.1.0.1'

##################################################

# http://bugly.qq.com/iosfast

  pod 'BuglyHotfix'

##################################################

# A missing placeholder for UITextView.
# https://github.com/devxoul/UITextView-Placeholder

# pod 'UITextView+Placeholder'

##################################################

# An in-app debugging and exploration tool for iOS
# https://github.com/Flipboard/FLEX

  pod 'FLEX', '~> 2.0', :configurations => ['Debug']

##################################################

# autolayout NSLayoutConstraints 简化版
# https://github.com/SnapKit/Masonry

  pod 'Masonry', '0.5.3'

##################################################

# 上拉 下拉 加载 刷新
# https://github.com/CoderMJLee/MJRefresh

  # pod 'MJRefresh'

##################################################

# 倒计时Label
# https://github.com/mineschan/MZTimerLabel

  # pod 'MZTimerLabel', :git => 'https://github.com/iosfeng/MZTimerLabel.git'

##################################################

# An extensible iOS and OS X animation library, useful for physics-based interactions.
# https://github.com/facebook/pop

  pod 'pop', '~> 1.0'

##################################################

# The "UINavigationController+JZExtension" category integrates some convenient functions and open some hide property for your UINavigationController.
# https://github.com/JazysYu/JZNavigationExtension

# pod 'JZNavigationExtension', :git => 'https://github.com/iosfeng/JZNavigationExtension'
# 安装指定的版本 不用 ~>
# pod 'JZNavigationExtension', '1.2.1'

# pod 'FDFullscreenPopGesture', '1.1'

##################################################

# Model framework for Cocoa and Cocoa Touch
# https://github.com/Mantle/Mantle

# pod 'Mantle'

##################################################

# 版本更新控制 自动更新的第三方库
# 地址: https://github.com/nicklockwood/iVersion

  pod 'iVersion'

##################################################

# 地址: https://github.com/nicklockwood/SwipeView
# SwipeView is a class designed to simplify the implementation of horizontal, paged scrolling views on iOS.

# pod 'SwipeView'

##################################################

# 地址: https://github.com/aaronn/UIView-Borders
# Easy one-sided and offset borders on all UIViews.

# pod 'UIView+Borders'

##################################################

# 地址: http://github.com/zsk425/SKTagView
# 方便地实现 标签 选择的功能。

# pod 'SKTagView'

##################################################

# https://github.com/shu223/PulsingHalo
# iOS Component For Creating A Pulsing Animation. 雷达效果

# pod 'PulsingHalo'

##################################################

# https://github.com/jivadevoe/UIAlertView-Blocks
# A category for UIAlertView which allows you to use
# blocks to handle the pressed button events rather than implementing a delegate.

  # pod 'UIAlertView-Blocks'

##################################################

# https://github.com/jessesquires/JSQMessagesViewController
# An elegant messages UI library for iOS http://jessesquires.com/JSQMessagesViewController

# pod 'JSQMessagesViewController'

##################################################

# https://github.com/dustturtle/RealReachability
# REAL reachability of network
# 暂不用这个 目前不是特别地稳定,再==

# pod 'RealReachability'

##################################################

# 取决于你的工程如何组织，你的node_modules文件夹可能会在别的地方。
# 请将:path后面的内容修改为正确的路径。
#pod 'React'
#pod "React/RCTText"
#pod "React/RCTNetwork"
#pod "React/RCTWebSocket"
#pod "React/RCTImage"

##################################################

# 用Libs的方式了
# https://github.com/bang590/JSPatch

# pod 'JSPatch'

##################################################

# An iOS/OSX bridge for sending messages between Obj-C and JavaScript in UIWebViews/WebViews http://marcuswest.in
# https://github.com/marcuswestin/WebViewJavascriptBridge

# pod 'WebViewJavascriptBridge', '~> 5.0'

##################################################

# https://github.com/shaojiankui/JKCategories

# pod 'JKCategories'

##################################################

# https://github.com/facebook/KVOController

  pod 'KVOController'

##################################################

# VTMagic is a page container library for iOS.
# https://github.com/tianzhuo112/VTMagic

  # pod 'VTMagic'
# pod 'PageMenu'

##################################################

# AppDevKit is an iOS development library that provides
# developers with useful features to fulfill their everyday iOS app development needs.
# https://yahoo.github.io/AppDevKit
# https://github.com/yahoo/AppDevKit

# pod 'AppDevKit'

##################################################

# https://github.com/dzenbot/DZNEmptyDataSet

  pod 'DZNEmptyDataSet'

##################################################

# https://github.com/LeoiOS/LCTabBarController/blob/master/README_zh-CN.md

# pod 'LCTabBarController'

##################################################

# 高斯模糊
# 地址: https://github.com/lukabernardi/LBBlurredImage

# pod 'LBBlurredImage'

##################################################
# 后台服务
# http://www.bmob.cn
# pod 'BmobSDK'
##################################################

# server
# https://leancloud.cn/docs/sdk_setup-objc.html

# pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
# pod 'AVOSCloudIM'             # 实时通信模块
# pod 'AVOSCloudCrashReporting' # 错误报告模块

##################################################

# https://github.com/ccgus/fmdb
  pod 'FMDB' #, '2.6'

##################################################

# https://github.com/CocoaLumberjack/CocoaLumberjack
# A fast & simple, yet powerful & flexible logging framework for Mac and iOS
  pod 'CocoaLumberjack'

##################################################

# https://github.com/MortimerGoro/MGSwipeTableCell
# An easy to use UITableViewCell subclass that allows to display swippable buttons with a variety of transitions.
#   pod 'MGSwipeTableCell'

##################################################

# https://github.com/cwRichardKim/RKNotificationHub
  pod 'RKNotificationHub'

##################################################

# 高斯模糊2
# 地址:https://github.com/nicklockwood/FXBlurView

  pod 'FXBlurView'

##################################################

# https://github.com/forkingdog/UITableView-FDTemplateLayoutCell
# 自动高度计算
  pod 'UITableView+FDTemplateLayoutCell'

##################################################

# https://github.com/ViccAlexander/Chameleon
  pod 'ChameleonFramework'

# https://github.com/bennyguitar/Colours
# pod 'Colours' # 和上面的库有冲突

##################################################

#  pod 'FYHelper'

##################################################

# 不错的用户反馈
# https://dashboard.instabug.com/applications/iosfeng/beta/
# https://dashboard.instabug.com/profile/
  pod 'Instabug'

  ##################################################


end
